Fix accident date placeholder
cafm-imss/cafm-ims-saas pull request #55
Opened 2023-12-10 08:34 UTC by mahmoudmagdy10

2023-12-10 12:05 UTC, mahmoudmagdy10 commented
https://projects.cafm-ims.com/browse/CAFM-32

2023-12-12 15:06 UTC, HamzaMansouri7 requested changes

2023-12-12 15:06 UTC, HamzaMansouri7 commented on src/app/pages/accident-reports/accident-reports.component.html
> +      <div class="card-title m-0">
please fix : 

![image](https://github.com/cafm-imss/cafm-ims-saas/assets/51540362/ee75e0ac-b975-425b-a813-c3b1a19c0ed9)

2023-12-12 22:47 UTC, HamzaMansouri7 approved these changes

2023-12-13 17:55 UTC, merged